### model
model_name_or_path: /Model/Weight/Qwen2.5-14B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 64
lora_target: all

### dataset
dataset: bw_gen, bw_ed, bw_info_spe , bw_info
dataset_dir: /Code/LLaMA-Factory/data
template: qwen
cutoff_len: 3072
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 8

### output
output_dir: /Model/LoRA/Qwen2.5_BW/20250613_v4
logging_steps: 1
save_steps: 2500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb

### train
per_device_train_batch_size: 32
gradient_accumulation_steps: 4
learning_rate: 5.0e-4
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.01
fp16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
val_size: 0.1
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 50