### model
model_name_or_path: /Model/Weight/Qwen2.5-VL-7B-Instruct/
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 32
lora_target: all

### dataset
dataset: mwh_wov, coig, mo_qa, mo_vqa, cc3m_vqa, mo_caption
dataset_dir: /Code/LLaMA-Factory/data
template: qwen2_vl
cutoff_len: 3072
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: /Model/LoRA/Qwen2.5_VL_MO/20250519_v2
logging_steps: 1
save_steps: 2500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 4
freeze_vision_tower: true
learning_rate: 1.0e-4
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.02
fp16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
val_size: 0.1
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 50